# - name: Add nginx repository
#   ansible.builtin.apt_repository:
#     repo: deb http://nginx.org/packages/mainline/ubuntu/ bionic nginx
#     state: present
#     filename: nginx
#     update_cache: true

- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Copy nginx config file
  ansible.builtin.template:
    src: portfolio.conf.j2
    dest: /etc/nginx/conf.d/portfolio.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart nginx

- name: Create ssl certs directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: Generate dhparams
  community.crypto.openssl_dhparam:
    path: /etc/nginx/ssl/dhparam.pem
    size: 4096
    force: false

- name: Start and enable service nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
