- name: Add nginx repository
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/ubuntu/ bionic nginx
    state: present
    filename: nginx
    update_cache: yes

- name: Install nginx
  apt:
    name: nginx

- name: Copy nginx config file
  template:
    src: portfolio.conf.j2
    dest: /etc/nginx/conf.d/portfolio.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Create ssl certs directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0755

- name: Generate dhparams
  openssl_dhparam:
    path: /etc/nginx/ssl/dhparam.pem
    size: 4096
    force: no

- name: start and enable service nginx
  systemd:
    name: nginx
    state: started
    enabled: yes