---
- hosts: production
  gather_facts: no
  become: true
  vars:
    user: paul
    domain_name: "paul.michaud.bzh"
    ssl_certificate: "/etc/nginx/ssl/fullchain.pem"
    ssl_certificate_key: "/etc/nginx/ssl/privkey.pem"
  remote_user: "{{ user }}"
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python
  roles:
    - { role: packages, tags: packages }
    - { role: html, tags: html }
    - { role: css, tags: css }
    - { role: js, tags: js }
    - { role: nginx, tags: nginx }
    - { role: docker, tags: docker }
    - { role: gotty, tags: gotty }
    - { role: tools, tags: tools }
