---
- hosts: production
  gather_facts: true
  become: true
  vars:
    user: "paul"
    domain_name: "paul.michaud.bzh"
    ssl_certificate: "/etc/nginx/ssl/fullchain.pem"
    ssl_certificate_key: "/etc/nginx/ssl/privkey.pem"
  remote_user: "{{ user }}"
  pre_tasks:
    - name: "Install python"
      ansible.builtin.raw: sudo apt-get -y install python
      changed_when: false
  roles:
    - { role: web, tags: web }
    - { role: nginx, tags: nginx }
    - { role: docker, tags: docker }
    - { role: gotty, tags: gotty }
    - { role: tools, tags: tools }
