---
- hosts: production
  gather_facts: no
  vars:
    user: paul
    domain_name: "paul.michaud.bzh"
    ssl_certificate: "/etc/nginx/ssl/fullchain.pem"
    ssl_certificate_key: "/etc/nginx/ssl/privkey.pem"
  remote_user: "{{ user }}"
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python
  roles:
    - packages
    - html
    - css
    - js
    - nginx
    - docker
    - gotty
    - tools

  become: true
