---
- hosts: all
  name: Deploy portfolio
  gather_facts: true
  become: true
  remote_user: "{{ user }}"
  pre_tasks:
    - name: "Install python"
      ansible.builtin.raw: sudo apt-get -y install python3
      changed_when: false
  roles:
    - {role: web, tags: web}
    - {role: nginx, tags: nginx}
    - {role: docker, tags: docker}
    - {role: gotty, tags: gotty}
    - {role: tools, tags: tools}
