- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install docker
  apt:
    name: docker

- name: Install nginx
  apt:
    name: nginx

- name: Install go
  apt:
    name: golang