- name: Install go
  ansible.builtin.apt:
    name: golang

- name: Get gotty from source
  ansible.builtin.command: go get github.com/yudai/gotty
  become: false
  changed_when: false

- name: Copy gotty service file
  ansible.builtin.template:
    src: gotty.service.j2
    dest: /etc/systemd/system/gotty.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Systemd reload

- name: Create gotty config directory
  ansible.builtin.file:
    path: "/home/{{ user }}/portfolio/gotty/"
    state: directory
    mode: 0755

- name: Copy gotty config file
  ansible.builtin.copy:
    src: gotty.config
    dest: "/home/{{ user }}/portfolio/gotty/.gotty"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart gotty

- name: Enable and start service gotty
  ansible.builtin.systemd:
    name: gotty
    enabled: true
    state: started
