- name: Download gotty executable
  ansible.builtin.unarchive:
    # src: https://github.com/yudai/gotty/releases/download/v2.0.0-alpha.3/gotty_2.0.0-alpha.3_linux_amd64.tar.gz
    src: https://github.com/sorenisanerd/gotty/releases/download/v1.5.0/gotty_v1.5.0_linux_amd64.tar.gz
    dest: "/home/{{ user }}/go/bin/"
    remote_src: true
  become: false
  notify:
    - Restart gotty

- name: Copy gotty service file
  ansible.builtin.template:
    src: gotty.service.j2
    dest: /etc/systemd/system/gotty.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Systemd reload

- name: Create gotty config directory
  ansible.builtin.file:
    path: "/home/{{ user }}/portfolio/gotty/"
    state: directory
    mode: "0755"

- name: Copy gotty config file
  ansible.builtin.copy:
    src: gotty.config
    dest: "/home/{{ user }}/portfolio/gotty/.gotty"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart gotty

- name: Enable and start service gotty
  ansible.builtin.systemd:
    name: gotty
    enabled: true
    state: started
