- name: Install go
  apt:
    name: golang

- name: Get gotty from source
  command: go get github.com/yudai/gotty
  become: no
  changed_when: False

- name: Copy gotty service file
  template:
    src: gotty.service.j2
    dest: /etc/systemd/system/gotty.service
    owner: root
    group: root
  notify:
    - systemd reload

- name : Create gotty config directory
  file:
    path: "/home/{{ user }}/portfolio/gotty/"
    state: directory
    mode: 0755

- name: Copy gotty config file
  copy:
    src: gotty.config
    dest: "/home/{{ user }}/portfolio/gotty/.gotty"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart gotty

- name: enable and start service gotty
  systemd:
    name: gotty
    enabled: yes
    state: started
