- name: Copy log script
  ansible.builtin.copy:
    src: getlogs.sh
    dest: /usr/local/bin/getlogs.sh
    owner: root
    group: root
    mode: 0750

- name: Add logging job to crontab
  ansible.builtin.cron:
    name: "Check portfolio containers"
    minute: "*/10"
    job: "/usr/local/bin/getlogs.sh >/dev/null 2>&1"
