- name: Install docker
  apt:
    name: docker.io

- name : Create linux directory
  file:
    path: /home/{{ user }}/portfolio/docker/linux/
    state: directory
    mode: 0755

- name : Create script directory
  file:
    path: /home/{{ user }}/portfolio/docker/scripts/
    state: directory
    mode: 0755

- name: Copy the necessary file to build the image
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user}}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: '.bashrc', dest: '/home/{{ user }}/portfolio/docker/linux/.bashrc', mode: '644' }
    - { src: 'all.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/all.sh', mode: '644' }
    - { src: 'skills.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/skills.sh', mode: '644' }
    - { src: 'contact.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/contact.sh', mode: '644' }
    - { src: 'cv.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/cv.sh', mode: '644' }
    - { src: 'certifications.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/certifications.sh', mode: '644' }
    - { src: 'experiences.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/experiences.sh', mode: '644' }
    - { src: 'help.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/help.sh', mode: '644' }
    - { src: 'info.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/info.sh', mode: '644' }
    - { src: 'paul.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/paul.sh', mode: '644' }
    - { src: 'projects.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/projects.sh', mode: '644' }
    - { src: 'Dockerfile', dest: '/home/{{ user }}/portfolio/docker/Dockerfile', mode: '644' }

- name: Build the portfolio image
  docker_image:
    name: portfolio
    build:
      path: /home/{{ user }}/portfolio/docker
      pull: yes
    state: present
    source: build
    force_source: yes

- name: Adding user that will run gotty to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes