- name: Install docker
  apt:
    name: docker.io

- name : Create linux directory
  file:
    path: /home/{{ user }}/portfolio/docker/linux/
    state: directory
    mode: 0755

- name : Create script directory
  file:
    path: /home/{{ user }}/portfolio/docker/scripts/
    state: directory
    mode: 0755

- name: Copy the necessary file to build the image
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '.bashrc', dest: '/home/{{ user }}/portfolio/docker/linux/.bashrc', mode: '644' }
    - { src: 'all.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/all.sh', mode: '644' }
    - { src: 'competences.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/competences.sh', mode: '644' }
    - { src: 'contact.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/contact.sh', mode: '644' }
    - { src: 'cv.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/cv.sh', mode: '644' }
    - { src: 'diplomes.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/diplomes.sh', mode: '644' }
    - { src: 'experiences.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/experiences.sh', mode: '644' }
    - { src: 'help.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/help.sh', mode: '644' }
    - { src: 'info.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/info.sh', mode: '644' }
    - { src: 'paul.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/paul.sh', mode: '644' }
    - { src: 'projets.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/projets.sh', mode: '644' }
    - { src: 'Dockerfile', dest: '/home/{{ user }}/portfolio/docker/Dockerfile', mode: '644' }

- name: Build the portfolio image
  command: docker build -t portfolio /home/{{ user }}/portfolio/docker
  changed_when: false

- name: Adding user that will run gotty to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes