- name: Install docker
  ansible.builtin.apt:
    name: docker.io

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started

- name: Install docker python package to use the ansible module
  ansible.builtin.pip:
    name: docker

- name: Create linux directory
  ansible.builtin.file:
    path: /home/{{ user }}/portfolio/docker/linux/
    state: directory
    mode: "0755"

- name: Create script directory
  ansible.builtin.file:
    path: /home/{{ user }}/portfolio/docker/scripts/
    state: directory
    mode: "0755"

- name: Copy the necessary file to build the image
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: 'linux/.bashrc', dest: '/home/{{ user }}/portfolio/docker/linux/.bashrc', mode: '644'}
    - {src: 'scripts/all.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/all.sh', mode: '644'}
    - {src: 'scripts/skills.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/skills.sh', mode: '644'}
    - {src: 'scripts/contact.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/contact.sh', mode: '644'}
    - {src: 'scripts/cv.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/cv.sh', mode: '644'}
    - {src: 'scripts/certifications.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/certifications.sh', mode: '644'}
    - {src: 'scripts/experiences.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/experiences.sh', mode: '644'}
    - {src: 'scripts/help.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/help.sh', mode: '644'}
    - {src: 'scripts/info.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/info.sh', mode: '644'}
    - {src: 'scripts/paul.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/paul.sh', mode: '644'}
    - {src: 'scripts/projects.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/projects.sh', mode: '644'}
    - {src: 'scripts/antarctica.sh', dest: '/home/{{ user }}/portfolio/docker/scripts/antarctica.sh', mode: '644'}
    - {src: 'Dockerfile', dest: '/home/{{ user }}/portfolio/docker/Dockerfile', mode: '644'}

- name: Build the portfolio image
  community.docker.docker_image:
    name: portfolio
    build:
      path: /home/{{ user }}/portfolio/docker
      pull: true
    state: present
    source: build
    force_source: true

- name: Adding user that will run gotty to docker group
  ansible.builtin.user:
    name: '{{ user }}'
    groups: docker
    append: true
