name: Ansible Lint & Deploy

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          targets: "main.yml"
          args: ""

  deploy:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [production]
            michaud.bzh
          options: |
            --verbose
      
