name: Ansible Lint & Deploy

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
              echo "Installing playbook prerequisites"
              ansible-galaxy collection install community.crypto
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        with:
          path: "main.yml"

  deploy:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [production]
            michaud.bzh
          options: |
            --verbose
      
